---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Gather Facts from aws
    ec2_remote_facts:
       region: us-east-1
       filters:
         "tag:owner": xxxxx@xxxx.com
    register: ec2_instances
  
  - name: Print registered variable ec2_instances
    debug: 
      var: ec2_instances

#  - pause:

  - name: Print filtered output
    debug: 
      msg: "{{ item.0 }} and {{ item.1 }} and {{ item.2}}"
    with_together:
      - "{{ ec2_instances.instances | map(attribute='tags.AnsibleGroup')| list }}"
      - "{{ ec2_instances.instances | map(attribute='public_ip_address')| list }}"
      - "{{ ec2_instances.instances | map(attribute='tags.Name')| list }}"

#  - pause:

  - name: Create In Memory Inventory
    add_host:
       group: "{{item.0}}"
       hostname: "{{item.2}}"
       ansible_host: "{{item.1}}"
       ansible_ssh_private_key_file: ~/.ssh/cloud-user.pem
       ansible_ssh_user: cloud-user
    with_together:
      - "{{ ec2_instances.instances | map(attribute='tags.AnsibleGroup')| list }}"
      - "{{ ec2_instances.instances | map(attribute='public_ip_address')| list }}"
      - "{{ ec2_instances.instances | map(attribute='tags.Name')| list }}"
  - debug: var=groups

#  - pause:

- name: Test play against In-memory inventory
  hosts: bastion
  gather_facts: false
  tasks:
    - ping:
      register: ping_output
    - debug: var=ping_output
 













